import 'dart:convert';
import 'package:http/http.dart' as http;
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import '../config/app_config.dart';

class ApiService {
  static const _storage = FlutterSecureStorage();

  // ================= UTILITIES & HEADERS =================

  static Future<Map<String, String>> getAuthIds() async {
    final token = await _storage.read(key: 'authToken');
    final userId = await _storage.read(key: 'userId');
    if (token == null || userId == null) {
      throw Exception('Authentication token or User ID not found. Please log in.');
    }
    return {'token': token, 'userId': userId};
  }
  
  static Future<Map<String, String>> _getHeaders({bool includeAuth = false}) async {
    final headers = {
      'Content-Type': 'application/json; charset=UTF-8',
    };
    if (includeAuth) {
      final token = await _storage.read(key: 'authToken');
      if (token != null) {
        headers['Authorization'] = 'Bearer $token';
      }
    }
    return headers;
  }
  
  static Map<String, dynamic> _handleResponse(http.Response response) {
    final contentType = response.headers['content-type'];
    if (contentType == null || !contentType.contains('application/json')) {
      return {
        'success': false,
        'message': 'Invalid response format',
        'statusCode': response.statusCode,
      };
    }

    final data = jsonDecode(response.body);
    if (response.statusCode >= 200 && response.statusCode < 300) {
      return {
        'success': true,
        'data': data,
        'statusCode': response.statusCode,
      };
    }
    return {
      'success': false,
      'message': data['message'] ?? 'Request failed',
      'data': data,
      'statusCode': response.statusCode,
    };
  }

  // ================= AUTH =================

  static Future<Map<String, dynamic>> signup({
    required String name,
    required String email,
    required String address,
    required String phone,
    required String password,
  }) async {
    final response = await http.post(
      Uri.parse(AppConfig.authSignupUrl),
      headers: await _getHeaders(),
      body: jsonEncode({
        'name': name,
        'email': email,
        'address': address,
        'phone': phone,
        'password': password,
      }),
    );
    return _handleResponse(response);
  }

  static Future<Map<String, dynamic>> signin({
    required String phone,
    required String password,
  }) async {
    final response = await http.post(
      Uri.parse(AppConfig.authSigninUrl),
      headers: await _getHeaders(),
      body: jsonEncode({
        'phone': phone,
        'password': password,
      }),
    );
    return _handleResponse(response);
  }

  /// UPDATED: Google Auth to match backend logic
  /// Sends the idToken generated by the Flutter GoogleSignIn plugin to the backend.
  static Future<Map<String, dynamic>> googleAuth({
    required String idToken,
  }) async {
    final response = await http.post(
      Uri.parse(AppConfig.authGoogleUrl),
      headers: await _getHeaders(),
      body: jsonEncode({
        'idToken': idToken,
      }),
    ).timeout(AppConfig.requestTimeout);
    
    final result = _handleResponse(response);

    // If login is successful, we store credentials locally immediately
    if (result['success'] == true && result['data'] != null) {
      final data = result['data'];
      if (data['token'] != null && data['user'] != null) {
        await storeUserCredentials(data['token'], data['user']['_id']);
      }
    }
    return result;
  }

  static Future<Map<String, dynamic>> verifyOTP({
    required String email,
    required String otp,
    required String tempToken,
  }) async {
    final response = await http.post(
      Uri.parse(AppConfig.authVerifyOtpUrl),
      headers: await _getHeaders(),
      body: jsonEncode({
        'email': email,
        'otp': otp,
        'tempToken': tempToken,
      }),
    );
    return _handleResponse(response);
  }

  static Future<Map<String, dynamic>> resendOTP({
    required String email,
    required String tempToken,
  }) async {
    final response = await http.post(
      Uri.parse(AppConfig.authResendOtpUrl),
      headers: await _getHeaders(),
      body: jsonEncode({
        'email': email,
        'tempToken': tempToken,
      }),
    );
    return _handleResponse(response);
  }

  static Future<Map<String, dynamic>> forgotPassword({
    required String email,
  }) async {
    final response = await http.post(
      Uri.parse(AppConfig.authForgotPasswordUrl),
      headers: await _getHeaders(),
      body: jsonEncode({'email': email}),
    );
    return _handleResponse(response);
  }

  static Future<Map<String, dynamic>> resetPassword({
    required String email,
    required String otp,
    required String tempToken,
    required String newPassword,
  }) async {
    final response = await http.post(
      Uri.parse(AppConfig.authResetPasswordUrl),
      headers: await _getHeaders(),
      body: jsonEncode({
        'email': email,
        'otp': otp,
        'tempToken': tempToken,
        'newPassword': newPassword,
      }),
    );
    return _handleResponse(response);
  }

  // ================= DATA & CONFIG =================
  
  static Future<Map<String, dynamic>> fetchAllApplicants() async {
    final response = await http.get(Uri.parse(AppConfig.formDataUrl));
    final handledResponse = _handleResponse(response);
    if (handledResponse['success'] == true) {
      final data = handledResponse['data'];
      if (data is Map && data.containsKey('data')) return {'success': true, 'data': data['data']};
      if (data is List) return {'success': true, 'data': data};
    }
    return handledResponse;
  }

  static Future<Map<String, dynamic>> fetchPricingPlans() async {
    final response = await http.get(Uri.parse(AppConfig.pricingPlansUrl));
    return _handleResponse(response);
  }
  
  static Future<Map<String, dynamic>> fetchCurrentUserProfile() async {
    final ids = await getAuthIds();
    final url = '${AppConfig.userProfileUrl}/${ids['userId']}'; 
    final response = await http.get(
      Uri.parse(url),
      headers: await _getHeaders(includeAuth: true),
    );
    return _handleResponse(response);
  }

  static Future<Map<String, dynamic>> addToFavorites(String applicantId) async {
    final ids = await getAuthIds();
    final url = '${AppConfig.userProfileUrl}/${ids['userId']}/favorites'; 
    final response = await http.post(
      Uri.parse(url),
      headers: await _getHeaders(includeAuth: true),
      body: jsonEncode({'applicantId': applicantId}),
    );
    return _handleResponse(response);
  }

  static Future<Map<String, dynamic>> removeFromFavorites(String applicantId) async {
    final ids = await getAuthIds();
    final url = '${AppConfig.userProfileUrl}/${ids['userId']}/favorites/$applicantId';
    final response = await http.delete(
      Uri.parse(url),
      headers: await _getHeaders(includeAuth: true),
    );
    return _handleResponse(response);
  }

  // ================= NEW: LOCATION SERVICES (GOOGLE MAPS) =================

  static Future<Map<String, dynamic>> reverseGeocode(double lat, double lng) async {
    final response = await http.post(
      Uri.parse(AppConfig.reverseGeocodeUrl),
      headers: await _getHeaders(includeAuth: true),
      body: jsonEncode({'latitude': lat, 'longitude': lng}),
    ).timeout(AppConfig.requestTimeout);
    return _handleResponse(response);
  }

  static Future<Map<String, dynamic>> geocodeAddress(String address) async {
    final response = await http.post(
      Uri.parse(AppConfig.geocodeUrl),
      headers: await _getHeaders(includeAuth: true),
      body: jsonEncode({'address': address}),
    ).timeout(AppConfig.requestTimeout);
    return _handleResponse(response);
  }

  static Future<Map<String, dynamic>> calculateDistance(String origin, String destination) async {
    final response = await http.post(
      Uri.parse(AppConfig.distanceMatrixUrl),
      headers: await _getHeaders(includeAuth: true),
      body: jsonEncode({'origin': origin, 'destination': destination}),
    ).timeout(AppConfig.requestTimeout);
    return _handleResponse(response);
  }

  // ================= PAYMENT =================

  static Future<Map<String, dynamic>> createRazorpayOrder({
    required int amountInPaise,
    String currency = 'INR',
  }) async {
    final ids = await getAuthIds(); 
    final response = await http.post(
      Uri.parse(AppConfig.razorpayOrderUrl), 
      headers: await _getHeaders(includeAuth: true),
      body: jsonEncode({
        'amount': amountInPaise,
        'currency': currency,
        'userId': ids['userId'], 
      }),
    );
    return _handleResponse(response);
  }

  // ================= STORAGE =================

  static Future<void> storeUserCredentials(String token, String userId) async {
    await _storage.write(key: 'authToken', value: token);
    await _storage.write(key: 'userId', value: userId);
  }

  static Future<void> clearUserCredentials() async {
    await _storage.delete(key: 'authToken');
    await _storage.delete(key: 'userId');
  }
}